{{- range .Values.groundStations }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .nodeId | lower }}
  namespace: {{ $.Values.namespace }}
  labels:
    nodalarc.io/node-id: {{ .nodeId }}
    nodalarc.io/role: ground_station
    nodalarc.io/gs-name: {{ .gsName }}
spec:
  containers:
    - name: frr
      image: {{ $.Values.images.frr }}
      imagePullPolicy: {{ $.Values.imagePullPolicy }}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
      resources:
        limits:
          memory: {{ $.Values.groundStation.memoryLimit }}
          cpu: {{ $.Values.groundStation.cpuLimit }}
  restartPolicy: Never
{{- end }}
