apiVersion: v1
kind: Service
metadata:
  name: nodalpath
  namespace: {{ .Values.namespace }}
  labels:
    app: nodalarc-nodalpath
spec:
  type: NodePort
  selector:
    app: nodalarc-nodalpath
  ports:
    - name: console
      port: 3100
      targetPort: 3100
      nodePort: 31100
      protocol: TCP
