apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodalarc-ome
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodalarc-ome-runtime-config
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodalarc-ome-runtime-config
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nodalarc-ome-runtime-config
subjects:
  - kind: ServiceAccount
    name: nodalarc-ome
    namespace: {{ .Values.namespace }}
