{{- range .Values.satellites }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .nodeId }}
  namespace: {{ $.Values.namespace }}
  labels:
    nodalarc.io/node-id: {{ .nodeId }}
    nodalarc.io/role: satellite
    nodalarc.io/plane: "{{ .plane }}"
    nodalarc.io/slot: "{{ .slot }}"
spec:
  containers:
    - name: frr
      image: {{ $.Values.images.frr }}
      imagePullPolicy: {{ $.Values.imagePullPolicy }}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
      resources:
        limits:
          memory: {{ $.Values.satellite.memoryLimit }}
          cpu: {{ $.Values.satellite.cpuLimit }}
  restartPolicy: Never
{{- end }}
