{{- range .Values.satellites }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .nodeId | lower }}
  namespace: {{ $.Values.namespace }}
  labels:
    nodalarc.io/node-id: {{ .nodeId }}
    nodalarc.io/role: satellite
    nodalarc.io/plane: "{{ .plane }}"
    nodalarc.io/slot: "{{ .slot }}"
spec:
  containers:
    - name: frr
      image: {{ $.Values.images.frr }}
      imagePullPolicy: {{ $.Values.imagePullPolicy }}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
      resources:
        limits:
          memory: {{ $.Values.satellite.memoryLimit }}
          cpu: {{ $.Values.satellite.cpuLimit }}
{{- if $.Values.sidecar }}
    - name: {{ $.Values.sidecar.image | replace ":" "-" | lower }}
      image: {{ $.Values.sidecar.image }}
      imagePullPolicy: {{ $.Values.imagePullPolicy }}
      securityContext:
        capabilities:
          add:
{{- range $.Values.sidecar.capabilities }}
            - {{ . }}
{{- end }}
{{- if .env }}
      env:
{{- range .env }}
        - name: {{ .name }}
          value: "{{ .value }}"
{{- end }}
{{- end }}
      resources:
        limits:
          memory: {{ $.Values.satellite.memoryLimit }}
          cpu: {{ $.Values.satellite.cpuLimit }}
{{- end }}
  restartPolicy: Never
{{- end }}
