apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodalarc-vf
  namespace: {{ .Values.namespace }}
  labels:
    app: nodalarc-vf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodalarc-vf
  template:
    metadata:
      labels:
        app: nodalarc-vf
    spec:
      containers:
        - name: vf
          image: {{ .Values.images.vf | default "docker.io/nodalarc/vf:latest" }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
              hostPort: 3000
              name: http
          resources:
            limits:
              memory: {{ .Values.vf.memoryLimit | default "128Mi" }}
              cpu: {{ .Values.vf.cpuLimit | default "100m" }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodalarc-vf
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nodalarc-vf
  ports:
    - port: 80
      targetPort: 80
      name: http
