apiVersion: v1
kind: Service
metadata:
  name: nodalarc-vs-api
  namespace: {{ .Values.namespace }}
  labels:
    app: nodalarc-vs-api
spec:
  selector:
    app: nodalarc-vs-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
