ground_station:
  name: ashburn
  lat_deg: 39.04
  lon_deg: -77.49
  alt_m: 100
  terminals:
    - type: optical
      count: 2
      bandwidth_mbps: 1000
      tracking_capacity: 1
  terrestrial_prefixes:
    - prefix: "172.16.2.0/24"
      metric: 10
    - prefix: "0.0.0.0/0"
      metric: 100
