# Copyright 2024-2026 .chance (dotchance)
# Licensed under the NodalArc Source Available License 1.0. See LICENSE file.
ground_station:
  name: djibouti
  lat_deg: 11.55
  lon_deg: 43.15
  alt_m: 15
  min_elevation_deg: 15
  terminals:
    - type: rf
      count: 1
      bandwidth_mbps: 1000
      tracking_capacity: 1
  terrestrial_prefixes:
    - prefix: "172.16.12.0/24"
      metric: 10
    - prefix: "0.0.0.0/0"
      metric: 100
