ground_station:
  name: stanley
  lat_deg: -51.70
  lon_deg: -57.85
  alt_m: 5
  min_elevation_deg: 25
  terminals:
    - type: rf
      count: 2
      bandwidth_mbps: 1000
      tracking_capacity: 1
  terrestrial_prefixes:
    - prefix: "172.16.27.0/24"
      metric: 10
    - prefix: "0.0.0.0/0"
      metric: 100
