stack:
  name: frr-ospf-plain
  image: nodalarc/frr:10
  daemons:
    - zebra
    - ospfd
  config_templates:
    - src: zebra.conf.j2
      dst: /etc/frr/zebra.conf
    - src: ospfd.conf.j2
      dst: /etc/frr/ospfd.conf
  template_variables:
    reference_bandwidth: 10000
  mi_adapter: frr_ospf_adapter
  max_compression: 10
  reconfigure_command: "vtysh -f {config_path}"
