stack:
  name: frr-ospf-te-mpls
  image: nodalarc/frr:10
  daemons:
    - zebra
    - ospfd
    - ldpd
  config_templates:
    - src: zebra.conf.j2
      dst: /etc/frr/zebra.conf
    - src: ospfd.conf.j2
      dst: /etc/frr/ospfd.conf
    - src: ldpd.conf.j2
      dst: /etc/frr/ldpd.conf
  template_variables:
    reference_bandwidth: 10000
  segment_routing: false
  mi_adapter: frr_ospf_adapter
  max_compression: 10
  reconfigure_command: "vtysh -f {config_path}"
