mode: explicit
name: 4-node-test
satellite_type: generic-2isl
satellites:
  - plane: 0
    slot: 0
    orbit:
      altitude_km: 550
      inclination_deg: 53
      raan_deg: 0
      true_anomaly_deg: 0
  - plane: 0
    slot: 1
    orbit:
      altitude_km: 550
      inclination_deg: 53
      raan_deg: 0
      true_anomaly_deg: 30
  - plane: 1
    slot: 0
    orbit:
      altitude_km: 550
      inclination_deg: 53
      raan_deg: 30
      true_anomaly_deg: 6
  - plane: 1
    slot: 1
    orbit:
      altitude_km: 550
      inclination_deg: 53
      raan_deg: 30
      true_anomaly_deg: 36
