# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from node_agent.proto import node_agent_pb2 as node__agent__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in node_agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NodeAgentServiceStub:
    """The Node Agent runs as a DaemonSet on each K3s node.
    It executes privileged netlink operations against local pod namespaces.
    The Scheduler sends batched commands; the agent executes them concurrently.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchLinkDown = channel.unary_unary(
            "/nodalarc.node_agent.NodeAgentService/BatchLinkDown",
            request_serializer=node__agent__pb2.BatchLinkDownRequest.SerializeToString,
            response_deserializer=node__agent__pb2.BatchLinkDownResponse.FromString,
            _registered_method=True,
        )
        self.BatchLinkUp = channel.unary_unary(
            "/nodalarc.node_agent.NodeAgentService/BatchLinkUp",
            request_serializer=node__agent__pb2.BatchLinkUpRequest.SerializeToString,
            response_deserializer=node__agent__pb2.BatchLinkUpResponse.FromString,
            _registered_method=True,
        )
        self.SetLatency = channel.unary_unary(
            "/nodalarc.node_agent.NodeAgentService/SetLatency",
            request_serializer=node__agent__pb2.SetLatencyRequest.SerializeToString,
            response_deserializer=node__agent__pb2.SetLatencyResponse.FromString,
            _registered_method=True,
        )
        self.GetTopology = channel.unary_unary(
            "/nodalarc.node_agent.NodeAgentService/GetTopology",
            request_serializer=node__agent__pb2.GetTopologyRequest.SerializeToString,
            response_deserializer=node__agent__pb2.GetTopologyResponse.FromString,
            _registered_method=True,
        )


class NodeAgentServiceServicer:
    """The Node Agent runs as a DaemonSet on each K3s node.
    It executes privileged netlink operations against local pod namespaces.
    The Scheduler sends batched commands; the agent executes them concurrently.
    """

    def BatchLinkDown(self, request, context):
        """Bring down a batch of interfaces atomically.
        All operations execute concurrently. ACK returned when all complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchLinkUp(self, request, context):
        """Bring up a batch of interfaces with tc shaping and NDP resolution.
        All operations execute concurrently. ACK returned when all complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetLatency(self, request, context):
        """Update netem delay on active interfaces."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTopology(self, request, context):
        """Return observed interface state for reconciliation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NodeAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BatchLinkDown": grpc.unary_unary_rpc_method_handler(
            servicer.BatchLinkDown,
            request_deserializer=node__agent__pb2.BatchLinkDownRequest.FromString,
            response_serializer=node__agent__pb2.BatchLinkDownResponse.SerializeToString,
        ),
        "BatchLinkUp": grpc.unary_unary_rpc_method_handler(
            servicer.BatchLinkUp,
            request_deserializer=node__agent__pb2.BatchLinkUpRequest.FromString,
            response_serializer=node__agent__pb2.BatchLinkUpResponse.SerializeToString,
        ),
        "SetLatency": grpc.unary_unary_rpc_method_handler(
            servicer.SetLatency,
            request_deserializer=node__agent__pb2.SetLatencyRequest.FromString,
            response_serializer=node__agent__pb2.SetLatencyResponse.SerializeToString,
        ),
        "GetTopology": grpc.unary_unary_rpc_method_handler(
            servicer.GetTopology,
            request_deserializer=node__agent__pb2.GetTopologyRequest.FromString,
            response_serializer=node__agent__pb2.GetTopologyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nodalarc.node_agent.NodeAgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nodalarc.node_agent.NodeAgentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class NodeAgentService:
    """The Node Agent runs as a DaemonSet on each K3s node.
    It executes privileged netlink operations against local pod namespaces.
    The Scheduler sends batched commands; the agent executes them concurrently.
    """

    @staticmethod
    def BatchLinkDown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalarc.node_agent.NodeAgentService/BatchLinkDown",
            node__agent__pb2.BatchLinkDownRequest.SerializeToString,
            node__agent__pb2.BatchLinkDownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchLinkUp(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalarc.node_agent.NodeAgentService/BatchLinkUp",
            node__agent__pb2.BatchLinkUpRequest.SerializeToString,
            node__agent__pb2.BatchLinkUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetLatency(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalarc.node_agent.NodeAgentService/SetLatency",
            node__agent__pb2.SetLatencyRequest.SerializeToString,
            node__agent__pb2.SetLatencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTopology(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalarc.node_agent.NodeAgentService/GetTopology",
            node__agent__pb2.GetTopologyRequest.SerializeToString,
            node__agent__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
