# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from proto import forwarding_pb2 as forwarding__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in forwarding_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ForwardingServiceStub:
    """The service exposed by the custom MPLS container.
    NodalPath calls this to update forwarding tables.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateForwardingTable = channel.unary_unary(
            "/nodalpath.forwarding.ForwardingService/UpdateForwardingTable",
            request_serializer=forwarding__pb2.ForwardingTableUpdate.SerializeToString,
            response_deserializer=forwarding__pb2.PushResponse.FromString,
            _registered_method=True,
        )
        self.GetForwardingTable = channel.unary_unary(
            "/nodalpath.forwarding.ForwardingService/GetForwardingTable",
            request_serializer=forwarding__pb2.Empty.SerializeToString,
            response_deserializer=forwarding__pb2.ForwardingTableState.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/nodalpath.forwarding.ForwardingService/GetStatus",
            request_serializer=forwarding__pb2.Empty.SerializeToString,
            response_deserializer=forwarding__pb2.NodeStatus.FromString,
            _registered_method=True,
        )


class ForwardingServiceServicer:
    """The service exposed by the custom MPLS container.
    NodalPath calls this to update forwarding tables.
    """

    def UpdateForwardingTable(self, request, context):
        """Push a complete forwarding table update to the node.
        The node replaces its current forwarding state with the provided entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetForwardingTable(self, request, context):
        """Retrieve the node's current forwarding table."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Get the node's operational status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ForwardingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UpdateForwardingTable": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateForwardingTable,
            request_deserializer=forwarding__pb2.ForwardingTableUpdate.FromString,
            response_serializer=forwarding__pb2.PushResponse.SerializeToString,
        ),
        "GetForwardingTable": grpc.unary_unary_rpc_method_handler(
            servicer.GetForwardingTable,
            request_deserializer=forwarding__pb2.Empty.FromString,
            response_serializer=forwarding__pb2.ForwardingTableState.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=forwarding__pb2.Empty.FromString,
            response_serializer=forwarding__pb2.NodeStatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nodalpath.forwarding.ForwardingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nodalpath.forwarding.ForwardingService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ForwardingService:
    """The service exposed by the custom MPLS container.
    NodalPath calls this to update forwarding tables.
    """

    @staticmethod
    def UpdateForwardingTable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalpath.forwarding.ForwardingService/UpdateForwardingTable",
            forwarding__pb2.ForwardingTableUpdate.SerializeToString,
            forwarding__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetForwardingTable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalpath.forwarding.ForwardingService/GetForwardingTable",
            forwarding__pb2.Empty.SerializeToString,
            forwarding__pb2.ForwardingTableState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nodalpath.forwarding.ForwardingService/GetStatus",
            forwarding__pb2.Empty.SerializeToString,
            forwarding__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
