"""SGP4 reference fixture for future high-fidelity propagation gates.

NodalArc does not yet expose an SGP4/TLE OME propagator. This fixture locks
down a local, deterministic TLE reference generated by the `sgp4` dependency
so the eventual engine has a numeric release gate instead of a prose promise.
"""

from __future__ import annotations

import pytest
from sgp4.api import Satrec

ISS_TLE_LINE_1 = "1 25544U 98067A   21075.51041667  .00001264  00000-0  29660-4 0  9993"
ISS_TLE_LINE_2 = "2 25544  51.6442  21.5417 0002426  95.1670  21.8444 15.48974333273145"


@pytest.mark.parametrize(
    ("offset_s", "expected_r_km", "expected_v_km_s"),
    [
        (
            0.0,
            (-4251.971748597022, 2357.358738349331, 4740.4057076426725),
            (-5.557632235794692, -4.5159463531633115, -2.7313550530977366),
        ),
        (
            3600.0,
            (6508.565036110713, 1707.402506514798, -981.9621644319247),
            (-0.39186198852796383, 4.860355573318967, 5.905417820753693),
        ),
        (
            21600.0,
            (580.1044859144467, 4488.375601723018, 5061.453426970322),
            (-7.3458865911793065, -1.1516813754037765, 1.8576788694520805),
        ),
    ],
)
def test_iss_tle_sgp4_reference_positions(offset_s, expected_r_km, expected_v_km_s):
    sat = Satrec.twoline2rv(ISS_TLE_LINE_1, ISS_TLE_LINE_2)
    jd = sat.jdsatepoch + sat.jdsatepochF + offset_s / 86400.0

    error_code, position_km, velocity_km_s = sat.sgp4(jd, 0.0)

    assert error_code == 0
    assert position_km == pytest.approx(expected_r_km, abs=1e-9)
    assert velocity_km_s == pytest.approx(expected_v_km_s, abs=1e-12)
